M:font_manager
F:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_font_manager_draw_data_ZERO$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfont_manager.engine_font_manager_draw_char$x$1$22({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_char$y$1$22({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_char$ch$1$22({1}SC:U),R,0,0,[r7]
S:Lfont_manager.engine_font_manager_draw_char$pnt$1$23({3}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_char$tile$1$23({1}SC:U),R,0,0,[r7]
S:Lfont_manager.engine_font_manager_draw_text$x$1$24({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_text$y$1$24({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_text$text$1$24({3}DG,SC:U),R,0,0,[r5,r6,r7]
S:Lfont_manager.engine_font_manager_draw_text$pnt$1$25({3}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_text$idx$1$25({1}SC:U),R,0,0,[r3]
S:Lfont_manager.engine_font_manager_draw_text$tile$2$26({1}SC:S),R,0,0,[r2]
S:Lfont_manager.engine_font_manager_draw_data$x$1$27({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_data$y$1$27({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_data$data$1$27({2}SI:U),R,0,0,[r6,r7]
S:Lfont_manager.engine_font_manager_draw_data$pnt$1$28({3}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_data$idx$1$28({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_data$tile$1$28({1}SC:S),E,0,0
S:Lfont_manager.engine_font_manager_draw_data$quotient$1$28({2}SI:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_data$remainder$1$28({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_data$hold$1$28({4}DA4d,SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_data_ZERO$x$1$32({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_data_ZERO$y$1$32({1}SC:U),E,0,0
S:Lfont_manager.engine_font_manager_draw_data_ZERO$data$1$32({2}SI:U),R,0,0,[r6,r7]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$pnt$1$33({3}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$idx$1$33({1}SC:U),R,0,0,[r4]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$tile$1$33({1}SC:U),R,0,0,[r2]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$hold$1$33({4}DA4d,SC:U),E,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$font_tiles__palette__bin$0$0({0}DA0d,SC:U),D,0,0
S:G$font_tiles__tilemap__bin$0$0({0}DA0d,SC:U),D,0,0
S:G$font_tiles__tiles__psgcompr$0$0({0}DA0d,SC:U),D,0,0
S:G$sprites__palette__bin$0$0({0}DA0d,SC:U),D,0,0
S:G$sprites__tiles__psgcompr$0$0({0}DA0d,SC:U),D,0,0
S:G$tree_avoid__palette__bin$0$0({0}DA0d,SC:U),D,0,0
S:G$tree_avoid__tilemap__bin$0$0({0}DA0d,SC:U),D,0,0
S:G$tree_avoid__tiles__psgcompr$0$0({0}DA0d,SC:U),D,0,0
