M:font_manager
F:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfont_manager.engine_font_manager_draw_char$ch$1$40({1}SC:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_char$x$1$40({1}SC:U),B,1,5
S:Lfont_manager.engine_font_manager_draw_char$y$1$40({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_char$pnt$1$41({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_char$tile$1$41({1}SC:U),R,0,0,[c]
F:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfont_manager.engine_font_manager_draw_text$text$1$42({2}DG,SC:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_text$x$1$42({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_text$y$1$42({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_draw_text$pnt$1$43({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_text$idx$1$43({1}SC:U),R,0,0,[b]
S:Lfont_manager.engine_font_manager_draw_text$tile$2$44({1}SC:S),R,0,0,[e]
F:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),Z,0,5,0,0,0
S:Lfont_manager.engine_font_manager_draw_data$data$1$45({2}SI:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_data$x$1$45({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_data$y$1$45({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_draw_data$pnt$1$46({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_data$idx$1$46({1}SC:U),B,1,-6
S:Lfont_manager.engine_font_manager_draw_data$tile$1$46({1}SC:S),R,0,0,[c]
S:Lfont_manager.engine_font_manager_draw_data$quotient$1$46({2}SI:U),B,1,-5
S:Lfont_manager.engine_font_manager_draw_data$remainder$1$46({1}SC:U),R,0,0,[e]
S:Lfont_manager.engine_font_manager_draw_data$hold$1$46({4}DA4d,SC:U),B,1,-10
S:Lfont_manager.engine_font_manager_draw_data$sloc0$1$0({2}DD,SC:U),B,1,-2
S:Lfont_manager.engine_font_manager_draw_data$sloc1$1$0({1}SC:U),B,1,-3
S:Lfont_manager.engine_font_manager_draw_data$sloc2$1$0({2}SI:U),B,1,-5
F:G$engine_font_manager_draw_data_ZERO$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Lfont_manager.engine_font_manager_draw_data_ZERO$data$1$50({2}SI:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_data_ZERO$x$1$50({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_data_ZERO$y$1$50({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_draw_data_ZERO$pnt$1$51({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$idx$1$51({1}SC:U),R,0,0,[b]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$tile$1$51({1}SC:U),R,0,0,[e]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$hold$1$51({4}DA4d,SC:U),B,1,-6
S:Lfont_manager.engine_font_manager_draw_data_ZERO$sloc0$1$0({2}DD,SC:U),B,1,-2
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOffFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_SHOWDISPLAY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBackdropColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST08$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST18$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_loadTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_load1bppTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTilesatAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMapatAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGPaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_RGB$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_loadBGPaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysPressed$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysHeld$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysReleased$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_START$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
