M:font_manager
F:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfont_manager.engine_font_manager_draw_char$ch$1$22({1}SC:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_char$x$1$22({1}SC:U),B,1,5
S:Lfont_manager.engine_font_manager_draw_char$y$1$22({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_char$pnt$1$23({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_char$tile$1$23({1}SC:U),R,0,0,[c]
F:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfont_manager.engine_font_manager_draw_text$text$1$24({2}DG,SC:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_text$x$1$24({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_text$y$1$24({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_draw_text$pnt$1$25({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_text$idx$1$25({1}SC:U),R,0,0,[b]
S:Lfont_manager.engine_font_manager_draw_text$tile$2$26({1}SC:S),R,0,0,[e]
F:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),Z,0,5,0,0,0
S:Lfont_manager.engine_font_manager_draw_data$data$1$27({2}SI:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_data$x$1$27({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_data$y$1$27({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_draw_data$pnt$1$28({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_data$idx$1$28({1}SC:U),B,1,-6
S:Lfont_manager.engine_font_manager_draw_data$tile$1$28({1}SC:S),R,0,0,[c]
S:Lfont_manager.engine_font_manager_draw_data$quotient$1$28({2}SI:U),B,1,-3
S:Lfont_manager.engine_font_manager_draw_data$remainder$1$28({1}SC:U),R,0,0,[e]
S:Lfont_manager.engine_font_manager_draw_data$hold$1$28({4}DA4d,SC:U),B,1,-10
S:Lfont_manager.engine_font_manager_draw_data$sloc0$1$0({2}DD,SC:U),B,1,-5
S:Lfont_manager.engine_font_manager_draw_data$sloc1$1$0({1}SC:U),B,1,-1
S:Lfont_manager.engine_font_manager_draw_data$sloc2$1$0({2}SI:U),B,1,-3
F:G$engine_font_manager_draw_data_ZERO$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Lfont_manager.engine_font_manager_draw_data_ZERO$data$1$32({2}SI:U),B,1,4
S:Lfont_manager.engine_font_manager_draw_data_ZERO$x$1$32({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_draw_data_ZERO$y$1$32({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_draw_data_ZERO$pnt$1$33({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$idx$1$33({1}SC:U),R,0,0,[b]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$tile$1$33({1}SC:U),R,0,0,[e]
S:Lfont_manager.engine_font_manager_draw_data_ZERO$hold$1$33({4}DA4d,SC:U),B,1,-6
S:Lfont_manager.engine_font_manager_draw_data_ZERO$sloc0$1$0({2}DD,SC:U),B,1,-2
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
